### PR TITLE
Image size read from the SVG file.

### PR DESCRIPTION
**Pull request by claudio-rosati**
In my D&D application the user is expecting to see images at their original size, not 400x400.
This pull request addresses the problem reading the the width and height from SVG width and height or viewBox attributes.

### CODE REVIEW

**Comment by 0x4a616e** [comment]
Thanks for the PR, that would certainly be a good thing to have. I'm wondering however if there is no built-in functionality in batik that would support something similar. I've found [this](https://stackoverflow.com/questions/35162390/how-to-get-the-image-size-width-height-of-an-svg-image-with-batik) on SO, wich is probably easier for determining the actual width and size.

**Comment by claudio-rosati** [comment]
I have 2 comments about your one. 

The first one is about what is the _actual size_. I was just looking into the <svg...> attributes. Using batik seems to me returning something that could be different. 

The second comment is about the cons I’ve read in the linked page. My solution, probably verbose, is simpler. 

What do you think about

- refactoring a bit my code to make it smaller, and
- using the alternative as fallback if my code fails to determine the size?

**Comment by claudio-rosati** [comment]
@0x4a616e 
I've completed the implementation. Now if the `<svg ...>` element contains `width` and `height`, or `viewBox` my revised implementation will discover the image size quickly, otherwise the implementation you pointed out previously is used as fallback.

**Comment by RAnders00** [comment]
I see that the PR introduces mixed tabs and spaces. I think it would be appreciated if you could convert the spaces to tabs.

**Comment by claudio-rosati** [comment]
Oh, sorry... my NetBeans is now configured for a different style (I'm working in too many projects ;-)
I'll do now.

**Comment by claudio-rosati** [comment]
@RAnders00 
done

**Comment by 0x4a616e** [comment]
I went through the changes and I'm not so sure about this regular expression parsing. I think there are various cases in which this might yield wrong results, especially if there are comments involved. Thus, I'd rather go with actually parsing the SVG or relying on batiks own bounds calculation.
I'd also put all the sizing code into provider classes so that it can easily be changed or extended in the future. Maybe it'd also be an option to make it configurable which size calculation should be used. This might also be interesting to not change current behaviour, even though I don't think that people are actually relying on the current default size... 
I created a new branch where I added the size calculation from SO here: https://github.com/codecentric/javafxsvg/tree/actual-svg-size
This is however up for discussion, maybe we can put something together with the best of both approaches.

**Comment by claudio-rosati** [comment]
OK, I understand.
The problem is that the application I'm working on is using the default size because SVGs are specifically created to be good at their default size. Then users (engineers in my case) are free to resize the widget containing the image if necessary, but using the default size will reduce this occurrence drastically, while the current 400x400 force them to always resize the widget.
That said, when do you thing this feature will be available on Maven Central?

**Comment by 0x4a616e** [comment]
The version using the `GVTBuilder` taken from SO could be release rather quickly, maybe later today. I think i would make it configurable, as an "opt in" feature for now. Would that help you?

**Comment by claudio-rosati** [comment]
I'm fixing the regex to handle comments, ready in less than an hour (just few tests).
I'll commit it on this same pull request

**Comment by claudio-rosati** [comment]
As you can see from my fix, commented sections of the SVG file are now removed before processing for size extraction. The original (commented) stream is used for the fallback processing.

**Comment by 0x4a616e** [comment]
Thanks for the commit, but I think this can be done a lot simpler. Batik already parses the SVG and thus also knows about the documents `width` and `height` attribute. This can be accessed by just calling `document.getDocumentElement().getAttribute("width")` on the `org.w3c.dom.Document`. I think this is simpler and more resilient than doing manual parsing/pattern matching on the SVG code. I pushed an example on my branch mentioned above so you can have a look.

**Comment by claudio-rosati** [comment]
Yes I've seen it. I agree with you is simpler. The only thing is that you should check also for `viewBox`, in case `width` and 'height` are missing (like in `bacon.svg`).

**Comment by 0x4a616e** [comment]
Good hint, i'll add that

**Comment by 0x4a616e** [comment]
Are you sure that values from `viewBox` should be used for determining the dimensions of the SVG? As far as I understood the attribute, the view box is independent from the actual width and height of the image and just creates an internal coordinate system.

**Comment by claudio-rosati** [comment]
You are right, and if you now always use the batik fallback in case `width` and `height` are missing it should work fine. What I've seen is that in many cases `width` and `height` are missing and the `viewBox` is available containing the correct size of the image, this is why I have misinterpreted the specifications.

**Comment by claudio-rosati** [comment]
I've dug more in the SVG (2) specification and I've seen that probably only batik should be used, because `width` and `height` can be a simple number (interpreted in pixels), a percentage (number followed by `%`), a value with unit (like `100px`), and also `auto`.
So my idea of directly using those attributes is wrong.
Sorry for that.

**Comment by 0x4a616e** [comment]
Makes sense. The good thing about the approach i currently have on the branch is that it allows everyone to create their own fallback dimension provider in case the provided ones won't do. I'll try to release that today as soon as i've found my keys (somewhere on my old notebook) 😬

**Comment by claudio-rosati** [comment]
Thank you so much

**Comment by 0x4a616e** [comment]
I uploaded a new version:

    <dependency>
		<groupId>de.codecentric.centerdevice</groupId>
		<artifactId>javafxsvg</artifactId>
		<version>1.3.0</version>
	</dependency>

There is also a quick example in the readme on how to use the new dimension provider. I hope this works for you!

**Comment by claudio-rosati** [comment]
Thank you.
I'll use it as soon as it will appear on Maven Central.

**Pull request closed without merging**
